# spring session
spring:
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  redis:
    host: 10.10.101.161
    password:
    port: 6379
  security:
    user:
      password: password