# spring session
spring:
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  redis:
    host: 10.10.101.159
    password:
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 10

  security:
    user:
      password: password