# spring session
server:
  port: 9090
spring:
  application:
    name: beanchmark-oauth-sso
  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  redis:
    host: 10.10.101.161
    password:
    port: 6379
    lettuce:
      pool:
        max-idle: 10
        min-idle: 10
        max-active: 20
        max-wait: 10000
    timeout: 20000

security:
  oauth2:
    client:
      client-id: oauth-client
      client-secret: secret

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"